apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.webapp.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.webapp.name }}
    group: {{ .Values.webapp.group }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.webapp.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.webapp.name }}
      annotations:
        checksum/ingress: {{ .Values.ingress | toYaml | sha256sum }}
    spec:
      containers:
      - name: {{ .Values.webapp.name }}
        image: {{ .Values.webapp.container.image }}
        ports:
        - containerPort: {{ .Values.webapp.container.port }}
        env:
        - name: WELCOME_MESSAGE
          value: {{ .Values.webapp.welcomeMessage | quote }}
        - name: MAP_DATA_DIR
          value: {{ .Values.webapp.volume1.mountPath | quote }}
          #value: {{ .Values.webapp.dataDir | quote }}
        volumeMounts:
          - name: {{ .Values.webapp.volume1.name }}
            mountPath: {{ .Values.webapp.volume1.mountPath }}
            #mountPath: {{ .Values.webapp.dataDir }}
      volumes:
        - name: {{ .Values.webapp.volume1.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.webapp.volume1.name }}

