apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-demo
  namespace: visr
  annotations:
    cert-manager.io/cluster-issuer: incommon
spec:
  ingressClassName: nginx-internal
  rules:
  - host: visr-flask-demo.k8s.ucar.edu
    http:
      paths:
      # NEW map path (must be before "/")
      #- path: /map
      #  pathType: Prefix
      #  backend:
      #    service:
      #      name: flask-demo
      #      port:
      #        number: 5000

      # existing root path
      - path: /
        pathType: Prefix
        backend:
          service:
            name: flask-demo
            port:
              number: 5000
  tls:
  - hosts:
    - visr-flask-demo.k8s.ucar.edu
    secretName: visk-flask-tls
