apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: flask-demo
  namespace: visr
spec:
  ingressClassName: nginx-internal
  rules:
  - host: visr-flask-demo.k8s.ucar.edu
    http:
      paths:
      - backend:
          service:
            name: flask-demo
            port:
              number: 5000
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - visr-flask-demo.k8s.ucar.edu
    secretName: visk-flask-tls
