replicaCount: 1

webapp:
  enabled: true
  dataDir: /app/flask-app/data
  name: flask-demo
  group: flask-demo
  path: /
  welcomeMessage: "Welcome to the Flask Demo!"

  container: 
    #image: docker.io/ncging/argo-flask-demo:2025-08-08.11.09
    image: docker.io/sgpearse/flask-map-demo:0.0.5
    port: 5000

  volume1:
    name: output
    mountPath: /output
    size: 160Gi
